/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PlatformAdminRouteRouteImport } from './routes/platform-admin/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApproveTokenRouteImport } from './routes/approve.$token'
import { Route as OrdersAcknowledgeRouteImport } from './routes/orders.acknowledge'
import { Route as PlatformAdminIndexRouteImport } from './routes/platform-admin/index'
import { Route as PlatformAdminOrgIdRouteImport } from './routes/platform-admin/$orgId'
import { Route as QuoteTokenRouteImport } from './routes/quote/$token'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders/index'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders/$id'
import { Route as AuthenticatedRequisitionsIndexRouteImport } from './routes/_authenticated/requisitions/index'
import { Route as AuthenticatedRequisitionsIdRouteImport } from './routes/_authenticated/requisitions/$id'
import { Route as AuthenticatedRequisitionsNewRouteImport } from './routes/_authenticated/requisitions/new'
import { Route as AuthenticatedRfqsIndexRouteImport } from './routes/_authenticated/rfqs/index'
import { Route as AuthenticatedRfqsIdRouteImport } from './routes/_authenticated/rfqs/$id'
import { Route as ApiWebhooksPaymentRouteImport } from './routes/api/webhooks/payment'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRouteRoute = PlatformAdminRouteRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveTokenRoute = ApproveTokenRouteImport.update({
  id: '/approve/$token',
  path: '/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersAcknowledgeRoute = OrdersAcknowledgeRouteImport.update({
  id: '/orders/acknowledge',
  path: '/orders/acknowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminIndexRoute = PlatformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformAdminRouteRoute,
} as any)
const PlatformAdminOrgIdRoute = PlatformAdminOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => PlatformAdminRouteRoute,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/purchase-orders/$id',
    path: '/purchase-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequisitionsIndexRoute =
  AuthenticatedRequisitionsIndexRouteImport.update({
    id: '/requisitions/',
    path: '/requisitions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequisitionsIdRoute =
  AuthenticatedRequisitionsIdRouteImport.update({
    id: '/requisitions/$id',
    path: '/requisitions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequisitionsNewRoute =
  AuthenticatedRequisitionsNewRouteImport.update({
    id: '/requisitions/new',
    path: '/requisitions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfqsIndexRoute = AuthenticatedRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfqsIdRoute = AuthenticatedRfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWebhooksPaymentRoute = ApiWebhooksPaymentRouteImport.update({
  id: '/api/webhooks/payment',
  path: '/api/webhooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform-admin': typeof PlatformAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/api/health': typeof ApiHealthRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/orders/acknowledge': typeof OrdersAcknowledgeRoute
  '/platform-admin/$orgId': typeof PlatformAdminOrgIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/requisitions/$id': typeof AuthenticatedRequisitionsIdRoute
  '/requisitions/new': typeof AuthenticatedRequisitionsNewRoute
  '/rfqs/$id': typeof AuthenticatedRfqsIdRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/requisitions/': typeof AuthenticatedRequisitionsIndexRoute
  '/rfqs/': typeof AuthenticatedRfqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/api/health': typeof ApiHealthRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/orders/acknowledge': typeof OrdersAcknowledgeRoute
  '/platform-admin/$orgId': typeof PlatformAdminOrgIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/platform-admin': typeof PlatformAdminIndexRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/requisitions/$id': typeof AuthenticatedRequisitionsIdRoute
  '/requisitions/new': typeof AuthenticatedRequisitionsNewRoute
  '/rfqs/$id': typeof AuthenticatedRfqsIdRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/requisitions': typeof AuthenticatedRequisitionsIndexRoute
  '/rfqs': typeof AuthenticatedRfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/platform-admin': typeof PlatformAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/api/health': typeof ApiHealthRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/orders/acknowledge': typeof OrdersAcknowledgeRoute
  '/platform-admin/$orgId': typeof PlatformAdminOrgIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/platform-admin/': typeof PlatformAdminIndexRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/requisitions/$id': typeof AuthenticatedRequisitionsIdRoute
  '/_authenticated/requisitions/new': typeof AuthenticatedRequisitionsNewRoute
  '/_authenticated/rfqs/$id': typeof AuthenticatedRfqsIdRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/requisitions/': typeof AuthenticatedRequisitionsIndexRoute
  '/_authenticated/rfqs/': typeof AuthenticatedRfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform-admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/approvals'
    | '/dashboard'
    | '/deliveries'
    | '/invoices'
    | '/projects'
    | '/settings'
    | '/suppliers'
    | '/api/health'
    | '/approve/$token'
    | '/orders/acknowledge'
    | '/platform-admin/$orgId'
    | '/quote/$token'
    | '/platform-admin/'
    | '/purchase-orders/$id'
    | '/requisitions/$id'
    | '/requisitions/new'
    | '/rfqs/$id'
    | '/api/webhooks/payment'
    | '/api/webhooks/whatsapp'
    | '/purchase-orders/'
    | '/requisitions/'
    | '/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/approvals'
    | '/dashboard'
    | '/deliveries'
    | '/invoices'
    | '/projects'
    | '/settings'
    | '/suppliers'
    | '/api/health'
    | '/approve/$token'
    | '/orders/acknowledge'
    | '/platform-admin/$orgId'
    | '/quote/$token'
    | '/platform-admin'
    | '/purchase-orders/$id'
    | '/requisitions/$id'
    | '/requisitions/new'
    | '/rfqs/$id'
    | '/api/webhooks/payment'
    | '/api/webhooks/whatsapp'
    | '/purchase-orders'
    | '/requisitions'
    | '/rfqs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/platform-admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/invoices'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/api/health'
    | '/approve/$token'
    | '/orders/acknowledge'
    | '/platform-admin/$orgId'
    | '/quote/$token'
    | '/platform-admin/'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/requisitions/$id'
    | '/_authenticated/requisitions/new'
    | '/_authenticated/rfqs/$id'
    | '/api/webhooks/payment'
    | '/api/webhooks/whatsapp'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/requisitions/'
    | '/_authenticated/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformAdminRouteRoute: typeof PlatformAdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApproveTokenRoute: typeof ApproveTokenRoute
  OrdersAcknowledgeRoute: typeof OrdersAcknowledgeRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  ApiWebhooksPaymentRoute: typeof ApiWebhooksPaymentRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/$token': {
      id: '/approve/$token'
      path: '/approve/$token'
      fullPath: '/approve/$token'
      preLoaderRoute: typeof ApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/acknowledge': {
      id: '/orders/acknowledge'
      path: '/orders/acknowledge'
      fullPath: '/orders/acknowledge'
      preLoaderRoute: typeof OrdersAcknowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin/': {
      id: '/platform-admin/'
      path: '/'
      fullPath: '/platform-admin/'
      preLoaderRoute: typeof PlatformAdminIndexRouteImport
      parentRoute: typeof PlatformAdminRouteRoute
    }
    '/platform-admin/$orgId': {
      id: '/platform-admin/$orgId'
      path: '/$orgId'
      fullPath: '/platform-admin/$orgId'
      preLoaderRoute: typeof PlatformAdminOrgIdRouteImport
      parentRoute: typeof PlatformAdminRouteRoute
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requisitions/': {
      id: '/_authenticated/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof AuthenticatedRequisitionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requisitions/$id': {
      id: '/_authenticated/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/requisitions/$id'
      preLoaderRoute: typeof AuthenticatedRequisitionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requisitions/new': {
      id: '/_authenticated/requisitions/new'
      path: '/requisitions/new'
      fullPath: '/requisitions/new'
      preLoaderRoute: typeof AuthenticatedRequisitionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfqs/': {
      id: '/_authenticated/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof AuthenticatedRfqsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfqs/$id': {
      id: '/_authenticated/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/rfqs/$id'
      preLoaderRoute: typeof AuthenticatedRfqsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/payment': {
      id: '/api/webhooks/payment'
      path: '/api/webhooks/payment'
      fullPath: '/api/webhooks/payment'
      preLoaderRoute: typeof ApiWebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
  AuthenticatedRequisitionsIdRoute: typeof AuthenticatedRequisitionsIdRoute
  AuthenticatedRequisitionsNewRoute: typeof AuthenticatedRequisitionsNewRoute
  AuthenticatedRfqsIdRoute: typeof AuthenticatedRfqsIdRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedRequisitionsIndexRoute: typeof AuthenticatedRequisitionsIndexRoute
  AuthenticatedRfqsIndexRoute: typeof AuthenticatedRfqsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
  AuthenticatedRequisitionsIdRoute: AuthenticatedRequisitionsIdRoute,
  AuthenticatedRequisitionsNewRoute: AuthenticatedRequisitionsNewRoute,
  AuthenticatedRfqsIdRoute: AuthenticatedRfqsIdRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedRequisitionsIndexRoute: AuthenticatedRequisitionsIndexRoute,
  AuthenticatedRfqsIndexRoute: AuthenticatedRfqsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformAdminRouteRouteChildren {
  PlatformAdminOrgIdRoute: typeof PlatformAdminOrgIdRoute
  PlatformAdminIndexRoute: typeof PlatformAdminIndexRoute
}

const PlatformAdminRouteRouteChildren: PlatformAdminRouteRouteChildren = {
  PlatformAdminOrgIdRoute: PlatformAdminOrgIdRoute,
  PlatformAdminIndexRoute: PlatformAdminIndexRoute,
}

const PlatformAdminRouteRouteWithChildren =
  PlatformAdminRouteRoute._addFileChildren(PlatformAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformAdminRouteRoute: PlatformAdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApproveTokenRoute: ApproveTokenRoute,
  OrdersAcknowledgeRoute: OrdersAcknowledgeRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  ApiWebhooksPaymentRoute: ApiWebhooksPaymentRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
